version: "3.9"

services:

  postgres:
    image: postgres:latest
    restart: always

    user: postgres
    environment:
      POSTGRES_DB: budgetBuddyDB2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: JHQVUVb5auxUtwdTc8gX

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

    ports:
      - "8001:8001"
    volumes:
      - ./database:/docker-entrypoint-initdb.d

  api:
    build: api/.
    image: budgetbuddy-api
    restart: always
    
    environment:
      POSTGRES_IP: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: JHQVUVb5auxUtwdTc8gX
      POSTGRES_DB: budgetBuddyDB2
      FIREBASE_CREDENTIALS: /api_credentials/key.json

    ports:
      - "8000:8000"

    volumes:
      - ./src:/code
      - /home/maitane/firebase_credentials:/api_credentials

    depends_on:
      postgres:
        condition: service_healthy

    command: uvicorn app.main:app --host 0.0.0.0 --reload 
